export const artifactConfig = {
  artifactTypes: [
    { value: "1", label: "1" },
    { value: "2", label: "2" },
    { value: "3", label: "3" },
    { value: "4", label: "4" },
    { value: "5", label: "5" },
    { value: "6", label: "6" },
  ],
  mainStatsOptions: {
    1: [{ value: "HP", label: "HP" }],
    2: [{ value: "ATK", label: "ATK" }],
    3: [{ value: "DEF", label: "DEF" }],
    4: [
        { value: "%HP", label: "%HP" },
        { value: "%ATK", label: "%ATK" },
        { value: "%DEF", label: "%DEF" },
        { value: "Crit Rate", label: "Crit Rate" },
        { value: "Crit DMG", label: "Crit DMG" },
        { value: "AP", label: "Anomaly Proficiency" },
    ],
    5: [
        { value: "%HP", label: "%HP" },
        { value: "%ATK", label: "%ATK" },
        { value: "%DEF", label: "%DEF" },
        { value: "PEN Ratio", label: "PEN Ratio" },
        { value: "Physical", label: "Physical" },
        { value: "Electric", label: "Electric" },
        { value: "Ether", label: "Ether" },
        { value: "Fire", label: "Fire" },
        { value: "Ice", label: "Ice" },
    ],
    6: [
        { value: "%HP", label: "%HP" },
        { value: "%ATK", label: "%ATK" },
        { value: "%DEF", label: "%DEF" },
        { value: "AM", label: "Anomaly Mastery" },
        { value: "Impact", label: "Impact" },
        { value: "ER", label: "Energy Recharge" },
    ],
  } as Record<string, { value: string; label: string }[]>,
  allSubstats: ["HP", "%HP", "ATK", "%ATK", "DEF", "%DEF", "PEN", "AP", "Crit Rate", "Crit DMG"],
  scores: [
    "Complete trash",
    "Trash",
    "Usable",
    "Good",
    "Excellent",
    "Marvelous",
    "Unknown",
  ],
  sources: ["Routine Cleanup", "Music Store", "Music Store - Selected"],
  artifactSets: [
      "Astral Voice",
      "Branch & Blade Song",
      "Chaos Jazz",
      "Chaotic Metal",
      "Fanged Metal",
      "Freedom Blues",
      "Hormone Punk",
      "Inferno Metal",
      "Polar Metal",
      "Proto Punk",
      "Puffer Electro",
      "Shockstar Disco",
      "Soul Rock",
      "Swing Jazz",
      "Thunder Metal",
      "Woodpecker Electro",
      "Shadow Harmony",
      "Phaethon's Melody",
      "King of the Summit",
      "Yunkui Tales",
      "Moonlight Lullaby",
      "Dawn's Bloom",
      "White Water Ballad",
      "Shining Aria",
      "Bunny in Wonderland",
      "Notes From the Chained"
    ],
};
